lookahead_values: [5, 15]
features:
  - is_pivot_low_5
  - is_pivot_high_5
  - candle_range
  - rsi_6
  - atr_5
  - is_pivot_low_10
  - is_pivot_high_10
  - macd_fast_diff
  - atr_pct
  - return_1
  - macd_fast
  - volume
  - hour
  - chop_index
  - day_of_week

threshold_bounds: [0.0001, 0.01, 0.0005]
trading_params:
  tick_value: 5